$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths:
  - "**/build/**"
  - "**/macos/**"
words:
  - Seidel
  - Roguelike
  - autofocus
  - ARGB
  - Cupertino
  - Schyler
  - drawables
  - LTWH
  - scos
  - ssin
  - crossfade
  - Hitbox
  - platformer