name: factory_layout
description: A sample command-line application with basic argument parsing.
version: 0.0.1

environment:
  sdk: ^3.3.3

dependencies:
  collection: ^1.19.1
  mason_logger: ^0.2.15
  meta: ^1.14.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0  
  very_good_analysis: ^5.1.0
